version: '3.8'

services:
  greenhouse-ml:
    build: .
    container_name: greenhouse-ml
    ports:
      - "8000:8000"
    volumes:
      - ./Application/trained_models:/app/Application/trained_models
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
