version: '3.8'

services:
  greenhouse-ml:
    build:
      context: .
      dockerfile: Dockerfile
    image: greenhouse-ml
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Live code reloading
    container_name: greenhouse-ml
    environment:
      - PYTHONPATH=/app
    command: uvicorn Application.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - greenhouse-network

networks:
  greenhouse-network:
    external: true
