name: Test & Coverage

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # --- Checkout source code ---
    - name: Checkout source
      uses: actions/checkout@v3

    # --- Set up Python ---
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # --- Set PYTHONPATH so Python can find Application/ ---
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

    # --- Install main dependencies ---
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # --- Install test and linting tools ---
    - name: Install test tools
      run: |
        pip install flake8 pytest pytest-cov

    # --- Run flake8 lint checks ---
    - name: Run linting
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    # --- Run unit tests ---
    - name: Run tests
      run: |
        pytest

    # --- Run test coverage ---
    - name: Generate test coverage
      run: |
        pytest --cov=Application --cov-report=xml

    # --- Upload coverage to Codecov ---
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
