name: Test & Coverage

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest pytest-cov

    - name: Run linting
      run: |
        flake8 Application --count --select=E9,F63,F7,F82 --show-source --statistics || true

    - name: Run tests
      run: |
        PYTHONPATH=${{ github.workspace }} pytest Application/tests/

    - name: Generate test coverage
      run: |
        PYTHONPATH=${{ github.workspace }} pytest --cov=Application --cov-report=xml Application/tests/

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
